name: Build

on: [push]

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2.0.0
    - name: Dependencies
      run: sudo bash -s $GITHUB_WORKSPACE/cortex/dependencies.sh
    - name: Build project
      uses: nicledomaS/cmake_build_action@v1.4
      with:
        submodule_update: ON
        run_tests: OFF
      
